### ISSUE TITLE
Reduce npm package size

### ISSUE THREAD

**Issue by ai** [usmanyunusov/nanocolors-template#2]
Nano Colors uses [`clean-publish`](https://github.com/shashkovdanil/clean-publish) to clean `package.json` from development configs

**Comment by usmanyunusov** [comment]
Added `clean-publish` in commit https://github.com/usmanyunusov/nanocolors-template/commit/c857f7fa2442cd6663e2f6d69df964dc3fff099b99b

**Comment by ai** [comment]
You will need to use `npx clean-publish` instead of `npm publish`

**Comment by usmanyunusov** [comment]
Cool, 3.15 kB!
