### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by ai** [usmanyunusov/nanocolors-template#4]
- [x] Add short description about what project does
- [x] Uses this description in `package.json` and GitHub repo description
- [x] Add link to Nano Colors
- [x] Add more syntax description. For instance, how to escape `{`
- [x] Add keywords to `package.json`
- [x] Use Nano Colors logo in `README.md`

**Comment by usmanyunusov** [comment]
Updated docs in commit - https://github.com/usmanyunusov/nanocolors-template/commit/d790cb0f2b8dc6db389fe6803cf1bf564ecc4534
