### ISSUE TITLE
Keep ChangeLog

### ISSUE THREAD

**Issue by ai** [usmanyunusov/nanocolors-template#6]
ChangeLog has only version 0.0.1, but you already released 0.0.2 and 0.0.3 without notes in ChangeLog. It is bad.

Also, according to SemVer you should start from 0.1.0, not 0.0.1.

**Comment by ai** [comment]
I also recommend splitting changes and release commits. It allows finding npm releases in git history by looking for commits like `Release 0.0.3 version`.

**Comment by usmanyunusov** [comment]
Added ChangLog in commit - https://github.com/usmanyunusov/nanocolors-template/commit/d790cb0f2b8dc6db389fe6803cf1bf564ecc4534
