### ISSUE TITLE
picocolors version

### ISSUE THREAD

**Issue by ai** [usmanyunusov/nanocolors-template#8]
Since `nanocolors` was closed in flavor for `picocolors`, maybe you want to create `picocolors-template`?

**Comment by usmanyunusov** [comment]
I thought about this version.  Thoughts?

```js
import { createColorize } from 'colorize-template'
import * as picocolors from 'picocolors'

let colorize = createColorize({
  ...picocolors,
  success: picocolors.green,
  error: picocolors.red
})

colorize`Is red {red color} text`
colorize`Run {yellow.bgRed ${'yellow'} test}`
colorize`Is red {error error and {success green text}}`
```

**Comment by ai** [comment]
Cool idea

**Comment by usmanyunusov** [comment]
I think it can be used to replacing the `chalk` template in `picocolors`
Release 1.0.0: https://github.com/usmanyunusov/colorize-template/commit/9482194548a5fa5b1d5273d428e599d1d13d9ba4
